export const CART = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  DECREASE_QUANTITY_CART: "DECREASE_QUANTITY_CART",
  INCREASE_QUANTITY_CART: "INCREASE_QUANTITY_CART",
};

export const WISHLIST = {
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
};

export const SHOP = {
  SET_FILTER_CATEGORY: "SET_FILTER_CATEGORY",
  SET_FILTER_PRICE_RANGE: "SET_FILTER_PRICE_RANGE",
  SET_FILTER_BRAND: "SET_FILTER_BRAND",
  RESET_FILTER: "RESET_FILTER",
};

export const HOMECOMPONENTS = {
  GET_HOME_PAGE_COMPONENTS: "GET_HOME_PAGE_COMPONENTS",
  CLEAR_HOME_PAGE_COMPONENTS: "CLEAR_HOME_PAGE_COMPONENTS",
  SET_FILTER_CATEGORY_COMPONENTS: "SET_FILTER_CATEGORY_COMPONENTS",
  RESET_FILTER_COMPONENTS: "RESET_FILTER_COMPONENTS",
  UPDATE_SOURCE_COMPONENTS: "UPDATE_SOURCE_COMPONENTS",
  UPDATE_DESTINATION_COMPONENTS: "UPDATE_DESTINATION_COMPONENTS",
  CATEGORY_SOURCE_COMPONENTS: "CATEGORY_SOURCE_COMPONENTS",
};
